kind = "web"
previewPath = "/"
title = "Bolão Copa do Mundo 2026"
version = "1.0.0"
id = "artifacts/bolao2026"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22311

[services.development]
run = "pnpm --filter @workspace/bolao2026 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bolao2026", "run", "build" ]
publicDir = "artifacts/bolao2026/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22311"
BASE_PATH = "/"
